import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import profilePic from "../../public/images/profile/yash6.png";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
// import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/profile/home doodle.png";
import TransitionEffect from "@/components/TransitionEffect";
import HomePageComp from "@/components/HomePageComp";
// import fav1 from "../../public/images/favicon_io/apple-touch-icon.png";
// import fav2 from "../../public/images/favicon_io/favicon-32x32.png";
// import fav3 from "../../public/images/favicon_io/favicon-16x16.png";
export default function Home() {
  return (
    <>
      <Head>
        <title>Yash Shah | Portfolio</title>
        <meta name="description" content="Generated by create next app" />

        {/* <link
          rel="apple-touch-icon"
          sizes="180x180"
          href={fav1}
          type="image/x-icon"
        />
        <link rel="icon" type="image/png" sizes="32x32" href={fav2} />
        <link rel="icon" type="image/png" sizes="16x16" href={fav3} /> */}
        {/* <link rel="manifest" href={fav4} /> */}
      </Head>
      <TransitionEffect layoutEffect={false} />
      <main className="flex items-center text-[#f5f5f5] w-full sm:!overflow-x-hidden">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="!p-7 !px-24 w-[50%] md:!w-full sm:!p-6 sm:!w-full">
              <Image
                src={profilePic}
                alt="Yash Shah"
                className="w-full h-auto md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Licensed Enrolled Agent"
                className="!text-6xl !text-left !text-[#f5f5f5] xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <AnimatedText
                text="Tax Strategist"
                className="!text-6xl !text-left !text-[#eb6e00] xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-xl text-justify font-medium md:text-sm sm:!text-justify sm:text-xs">
                With a deep understanding of U.S. tax laws, Working on a
                contractual basis with CPAs during tax season to turn piles of
                numbers into perfectly filed returns. Think of me as your go-to
                tax season sidekick!
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/contact"
                  target="_blank"
                  className="flex items-center bg-[#eb6e00] text-[#f5f5f5] p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light  border-2 border-solid border-transparent hover:border-[#f5f5f5] md:p-2 md:px-4 md:text-base"
                >
                  Contact
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                {/* <Link
                  href="mailto:yashshahtaxfreelancer@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-[#f5f5f5] underline md:text-base"
                >
                  Contact
                </Link> */}
              </div>
            </div>
          </div>
          <HomePageComp />
        </Layout>
        {/* <HireMe /> */}
        <div className="fixed right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightBulb} alt="Yash Shah" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
